# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  command:  # id of input
    description: 'Command'
    required: true
    default: '--help'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
      - ${{ inputs.command }}
