# action.yml - https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'FlashPipe Snapshot Restore'
description: 'Restore snapshot contents of editable packages from Git repository to tenant'
author: 'engswee'
branding:
  icon: save
  color: blue
inputs:
  tmn-host:
    description: 'Host for tenant management node of Cloud Integration'
    required: true
  tmn-userid:
    description: 'User ID for Basic Auth'
    required: false
  tmn-password:
    description: 'Password for Basic Auth'
    required: false
  oauth-host:
    description: 'Host for OAuth token server'
    required: false
  oauth-clientid:
    description: 'Client ID for using OAuth'
    required: false
  oauth-clientsecret:
    description: 'Client Secret for using OAuth'
    required: false
  oauth-path:
    description: 'Path for OAuth token server'
    required: false
  dir-git-repo:
    description: 'Root directory of Git repository'
    required: false
    default: ${{ github.workspace }}
  dir-artifacts-relative:
    description: 'Directory containing contents of artifacts - relative to root directory of Git repository'
    required: false
  ids-include:
    description: 'List of included package IDs'
    required: false
  ids-exclude:
    description: 'List of excluded package IDs'
    required: false
  debug:
    description: 'Show debug logs'
    required: false

runs:
  using: "composite"
  steps:
    - run: flashpipe snapshot restore
      shell: bash
      env:
       FLASHPIPE_TMN_HOST: ${{ inputs.tmn-host }}
       FLASHPIPE_TMN_USERID: ${{ inputs.tmn-userid }}
       FLASHPIPE_TMN_PASSWORD: ${{ inputs.tmn-password }}
       FLASHPIPE_OAUTH_HOST: ${{ inputs.oauth-host }}
       FLASHPIPE_OAUTH_CLIENTID: ${{ inputs.oauth-clientid }}
       FLASHPIPE_OAUTH_CLIENTSECRET: ${{ inputs.oauth-clientsecret }}
       FLASHPIPE_OAUTH_PATH: ${{ inputs.oauth-path }}
       FLASHPIPE_DEBUG: ${{ inputs.debug }}
       FLASHPIPE_DIR_GIT_REPO: ${{ inputs.dir-git-repo }}
       FLASHPIPE_DIR_ARTIFACTS: ${{ inputs.dir-git-repo }}/${{ inputs.dir-artifacts-relative }}
       FLASHPIPE_IDS_INCLUDE: ${{ inputs.ids-include }}
       FLASHPIPE_IDS_EXCLUDE: ${{ inputs.ids-exclude }}
       FLASHPIPE_ACTION: true
