# action.yml - https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'FlashPipe Snapshot'
description: 'Snapshot contents of editable packages to Git repository'
author: 'engswee'
branding:
  icon: save
  color: blue
inputs:
  tmn-host:
    description: 'Host for tenant management node of Cloud Integration'
    required: true
  tmn-userid:
    description: 'User ID for Basic Auth'
    required: false
  tmn-password:
    description: 'Password for Basic Auth'
    required: false
  oauth-host:
    description: 'Host for OAuth token server'
    required: false
  oauth-clientid:
    description: 'Client ID for using OAuth'
    required: false
  oauth-clientsecret:
    description: 'Client Secret for using OAuth'
    required: false
  oauth-path:
    description: 'Path for OAuth token server'
    required: false
  dir-git-repo:
    description: 'Root directory of Git repository'
    required: false
    default: ${{ github.workspace }}
  draft-handling:
    description: 'Handling when artifact is in draft version. Allowed values: SKIP, ADD, ERROR (default "SKIP")'
    required: false
  git-commit-msg:
    description: 'Message used in commit (default "Tenant snapshot of <current_timestamp>")'
    required: false
  git-commit-user:
    description: 'User used in commit (default "github-actions[bot]")'
    required: false
  git-commit-email:
    description: 'Email used in commit (default "41898282+github-actions[bot]@users.noreply.github.com")'
    required: false
  sync-package-details:
    description: 'Sync details of Integration Package'
    required: false
  debug:
    description: 'Show debug logs'
    required: false

runs:
  using: "composite"
  steps:
    - run: flashpipe snapshot
      shell: bash
      env:
       FLASHPIPE_TMN_HOST: ${{ inputs.tmn-host }}
       FLASHPIPE_TMN_USERID: ${{ inputs.tmn-userid }}
       FLASHPIPE_TMN_PASSWORD: ${{ inputs.tmn-password }}
       FLASHPIPE_OAUTH_HOST: ${{ inputs.oauth-host }}
       FLASHPIPE_OAUTH_CLIENTID: ${{ inputs.oauth-clientid }}
       FLASHPIPE_OAUTH_CLIENTSECRET: ${{ inputs.oauth-clientsecret }}
       FLASHPIPE_OAUTH_PATH: ${{ inputs.oauth-path }}
       FLASHPIPE_DEBUG: ${{ inputs.debug }}
       FLASHPIPE_DIR_GIT_REPO: ${{ inputs.dir-git-repo }}
       FLASHPIPE_DRAFT_HANDLING: ${{ inputs.draft-handling }}
       FLASHPIPE_GIT_COMMIT_MSG: ${{ inputs.git-commit-msg }}
       FLASHPIPE_GIT_COMMIT_USER: ${{ inputs.git-commit-user }}
       FLASHPIPE_GIT_COMMIT_EMAIL: ${{ inputs.git-commit-email }}
       FLASHPIPE_SYNC_PACKAGE_DETAILS: ${{ inputs.sync-package-details }}
    - run: git push
      shell: bash
      env:
       HOME: /root
