on:
  push:
  workflow_dispatch:
    inputs:
      command:
        description: 'FlashPipe CLI command, e.g. update artifact, deploy, sync'
        required: true

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: FlashPipe action step
        uses: ./ # Uses an action in the root directory
        id: flashpipe
        with:
          command: ${{ inputs.command }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
